apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: production-app
  template:
    metadata:
      labels:
        app: production-app
    spec:
      containers:
      - name: production-container
        image: gcr.io/qwiklabs-gcp-04-848dbd459d7a/sample-app:v2.0
        ports:
        - containerPort: 8080
